(function(){
'use strict';
const KEY='neuroped_master_access_v1';
const STORE='np_consulta_docflow_v1';
const VERIFY='np_document_verifications_v1';
const TTL=12*60*60*1000;
const VERIFY_URL='https://jadsonfraga.github.io/neuroped/verificar-documento.html';
function master(){try{const v=JSON.parse(localStorage.getItem(KEY)||'{}');return v.ok&&Date.now()-Number(v.ts||0)<TTL}catch(e){return false}}
function g(id){return document.getElementById(id)}
function v(id){return g(id)?.value||''}
function set(id,val){if(g(id))g(id).value=val||''}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function patient(){return g('nome')?.value||'—'}
function dateBR(){return new Date().toLocaleDateString('pt-BR')}
function now(){return new Date().toISOString()}
function msg(t){if(g('docflowMsg'))g('docflowMsg').textContent=t}
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch(e){return{}}}
function save(){const d={};['docReceituario','docExames','docJustificativa','docLaudoFinalidade','docLaudoTexto'].forEach(id=>d[id]=v(id));localStorage.setItem(STORE,JSON.stringify(d));msg('Rascunhos documentais salvos localmente.')}
function header(type){return 'Dr. Jadson Fraga Araújo Júnior\nNeuropediatria · CRM-PE 25227 · RQE 17756\nAv. Cardoso de Sá, 1000 – Bairro Novo Centro – Petrolina/PE\n\n'+type+'\n\nPaciente: '+patient()+'\nData: '+dateBR()+'\n\n'}
function receituarioText(){return header('RECEITUÁRIO / ORIENTAÇÃO MÉDICA')+(v('docReceituario')||'Texto livre do médico responsável.')+'\n\nAssinatura e carimbo do médico\n'}
function examesText(){return header('SOLICITAÇÃO DE EXAMES')+'Exames solicitados:\n'+(v('docExames')||'—')+'\n\nJustificativa clínica:\n'+(v('docJustificativa')||'—')+'\n\nAssinatura e carimbo do médico\n'}
function laudoText(){return header('LAUDO / RELATÓRIO MÉDICO')+'Finalidade:\n'+(v('docLaudoFinalidade')||'—')+'\n\nTexto clínico:\n'+(v('docLaudoTexto')||'—')+'\n\nAssinatura e carimbo do médico\n'}
async function sha256(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(text||'')));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}
async function certify(kind,text){const created=now();const hash=await sha256(kind+'|'+patient()+'|'+created+'|'+text);const code='NP-'+created.slice(0,10).replace(/-/g,'')+'-'+hash.slice(0,10).toUpperCase();const url=VERIFY_URL+'?code='+encodeURIComponent(code)+'&hash='+encodeURIComponent(hash.slice(0,24));let list=[];try{list=JSON.parse(localStorage.getItem(VERIFY)||'[]')}catch(e){}list.unshift({code,hash,kind,patient:patient(),created,url});localStorage.setItem(VERIFY,JSON.stringify(list.slice(0,80)));return{code,hash,url,created}}
function qrSrc(url){return 'https://api.qrserver.com/v1/create-qr-code/?size=160x160&margin=8&data='+encodeURIComponent(url)}
function printDoc(title,text,cert){const w=window.open('','_blank');if(!w){msg('Pop-up bloqueado. Use copiar.');return}const qr=cert?'<div class="qr"><img src="'+qrSrc(cert.url)+'" alt="QR Code de conferência"><div><b>Código:</b> '+esc(cert.code)+'<br><b>Hash:</b> '+esc(cert.hash.slice(0,24))+'<br><b>Conferência:</b> '+esc(cert.url)+'</div></div>':'';w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>'+esc(title)+'</title><style>body{font-family:Arial,sans-serif;line-height:1.55;padding:34px;color:#111}pre{white-space:pre-wrap;font:15px Arial,sans-serif}.qr{display:flex;gap:16px;align-items:center;border:1px solid #ddd;border-radius:12px;padding:12px;margin-top:22px}.qr img{width:120px;height:120px}.warn{font-size:12px;color:#555;border-top:1px solid #ddd;margin-top:18px;padding-top:10px}@media print{body{padding:20mm}}</style></head><body><pre>'+esc(text)+'</pre>'+qr+'<div class="warn">QR e código são conferência local de integridade emitidos pelo NeuroPed. Não são assinatura digital ICP-Brasil e não substituem certificado digital A1/A3 ou validação jurídica em backend seguro.</div></body></html>');w.document.close();w.focus();setTimeout(()=>w.print(),250)}
function copy(text){navigator.clipboard.writeText(text).then(()=>msg('Texto copiado.')).catch(()=>msg('Não foi possível copiar.'))}
async function certPrint(kind,text,title){const cert=await certify(kind,text);printDoc(title,text,cert);msg('Documento com QR preparado. Código: '+cert.code)}
function history(){let list=[];try{list=JSON.parse(localStorage.getItem(VERIFY)||'[]')}catch(e){}g('docflowHistory').textContent=list.length?list.slice(0,8).map(x=>x.code+' · '+x.kind+' · '+new Date(x.created).toLocaleString('pt-BR')+'\n'+x.url).join('\n\n'):'Nenhum código gerado neste navegador.'}
function html(){return '<div class="card span12 no-print" id="docflowSuite"><h2>Documentos médicos avançados</h2><p class="muted">Receituário livre, solicitação de exames e laudos/relatórios com impressão limpa, opção “Salvar como PDF” e QR de conferência local. O sistema não sugere remédios, exames ou diagnósticos automaticamente.</p><p id="docflowMsg" class="status">Rascunhos locais protegidos por PIN master.</p></div><div class="card span6 no-print"><h2>Receituário livre</h2><label>Texto livre do médico</label><textarea id="docReceituario" placeholder="Digite manualmente o texto do receituário/orientação médica."></textarea><div class="actions"><button class="btn gold" id="copyReceituario">Copiar</button><button class="btn ghost" id="printReceituario">Imprimir / PDF</button><button class="btn" id="certReceituario">Imprimir com QR</button><button class="btn ghost" id="saveReceituario">Salvar</button></div></div><div class="card span6 no-print"><h2>Solicitação de exames</h2><label>Exames solicitados</label><textarea id="docExames" placeholder="Liste os exames conforme avaliação médica."></textarea><label>Justificativa clínica</label><textarea id="docJustificativa" placeholder="Justificativa objetiva da solicitação."></textarea><div class="actions"><button class="btn gold" id="copyExamesDoc">Copiar</button><button class="btn ghost" id="printExamesDoc">Imprimir / PDF</button><button class="btn" id="certExamesDoc">Imprimir com QR</button><button class="btn ghost" id="saveExamesDoc">Salvar</button></div></div><div class="card span12 no-print"><h2>Laudo / relatório com PDF</h2><label>Finalidade</label><textarea id="docLaudoFinalidade" placeholder="Ex.: escola, plano de saúde, terapias, acompanhamento"></textarea><label>Texto do laudo / relatório</label><textarea id="docLaudoTexto" placeholder="Redija o laudo conforme avaliação clínica. Use a impressão do navegador para salvar em PDF."></textarea><div class="actions"><button class="btn gold" id="copyLaudoFlow">Copiar</button><button class="btn ghost" id="printLaudoFlow">Imprimir / PDF</button><button class="btn" id="certLaudoFlow">Imprimir com QR</button><button class="btn ghost" id="saveLaudoFlow">Salvar</button><a class="btn ghost" href="./verificar-documento.html" target="_blank" rel="noopener">Verificador</a><button class="btn ghost" id="histDocFlow">Histórico local</button></div><pre id="docflowHistory" style="min-height:90px"></pre></div>'}
function inject(){if(!/consulta\.html/i.test(location.pathname))return false;if(!master())return false;if(g('docflowSuite'))return true;const grid=document.querySelector('#app .grid')||document.querySelector('section#app .grid');if(!grid)return false;const tmp=document.createElement('div');tmp.innerHTML=html();while(tmp.firstChild)grid.appendChild(tmp.firstChild);const d=load();Object.keys(d).forEach(k=>set(k,d[k]));['docReceituario','docExames','docJustificativa','docLaudoFinalidade','docLaudoTexto'].forEach(id=>g(id)?.addEventListener('input',save));g('copyReceituario').onclick=()=>copy(receituarioText());g('printReceituario').onclick=()=>printDoc('Receituário',receituarioText());g('certReceituario').onclick=()=>certPrint('RECEITUARIO',receituarioText(),'Receituário');g('saveReceituario').onclick=save;g('copyExamesDoc').onclick=()=>copy(examesText());g('printExamesDoc').onclick=()=>printDoc('Solicitação de exames',examesText());g('certExamesDoc').onclick=()=>certPrint('EXAMES',examesText(),'Solicitação de exames');g('saveExamesDoc').onclick=save;g('copyLaudoFlow').onclick=()=>copy(laudoText());g('printLaudoFlow').onclick=()=>printDoc('Laudo',laudoText());g('certLaudoFlow').onclick=()=>certPrint('LAUDO',laudoText(),'Laudo');g('saveLaudoFlow').onclick=save;g('histDocFlow').onclick=history;return true}
function boot(){inject();let n=0;const t=setInterval(()=>{n++;if(inject()||n>120)clearInterval(t)},700);document.addEventListener('click',()=>setTimeout(inject,150),true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();