-- NeuroPed EDJ — Supabase Schema (Postgres)
-- Execute em: SQL Editor do projeto Supabase

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  case_code text,
  patient_code text,
  instrument_id text not null,
  instrument_title text not null,
  answers jsonb not null default '{}'::jsonb,
  raw_score int,
  total_items int,
  source_page text,
  created_at timestamptz default now()
);

create index if not exists idx_subs_inst on public.submissions (instrument_id);
create index if not exists idx_subs_when on public.submissions (created_at desc);

create table if not exists public.consultas (
  id bigint generated by default as identity primary key,
  paciente text,
  idade text,
  queixa text,
  responsavel text,
  hpma text,
  conduta text,
  created_at timestamptz default now()
);

create table if not exists public.diario (
  id bigint generated by default as identity primary key,
  data date,
  tipo text,
  titulo text,
  texto text,
  created_at timestamptz default now()
);

-- RLS: ativar e criar policy de insert anônimo (para o app PWA)
alter table public.submissions enable row level security;
alter table public.consultas   enable row level security;
alter table public.diario      enable row level security;

drop policy if exists "anon insert subs" on public.submissions;
create policy "anon insert subs" on public.submissions for insert with check (true);

drop policy if exists "anon insert cons" on public.consultas;
create policy "anon insert cons" on public.consultas for insert with check (true);

drop policy if exists "anon insert diar" on public.diario;
create policy "anon insert diar" on public.diario for insert with check (true);

-- Leitura só para service_role (definida pelo backend / dashboard).
