const CACHE_NAME='neuroped-v49-featured-10-escalas';
const PRECACHE_URLS=['./','./index.html','./consulta.html','./portal-familia-livre.html','./central-atalhos.html','./verificar-app.html','./cloud-status.html','./cloud-config.example.js','./supabase/schema.sql','./manifest.json','./sw.js','./design-system-premium.css','./premium-polish-overrides.css','./editorial-impact.css','./premium-experience.js','./premium-polish.js','./assinatura-digital.html','./assinatura-digital.js','./comunicacao-alternativa.html','./diario-escola-terapias-v2.html','./filtro-escalas.html','./filtro-rank-pro.js','./mapa-escalas.html','./mapa-open-fix.js','./instrumento.html','./instrumento-453-loader.js','./featured-10-panel.js','./scales-featured-10.js','./scales-453-authorial.js','./scales-global-max.js','./scales-editorial.js','./scales-enhance.js','./scales-index.json','./escalas.html','./banco-escalas.html','./banco-escalas-lote1.html','./banco-escalas-lote2-80.html','./banco-escalas-lote3-100.html','./banco-escalas-lote4-200.html','./banco-escalas-lote5-90.html'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE_NAME).then(c=>Promise.allSettled(PRECACHE_URLS.map(u=>c.add(u)))).then(()=>self.skipWaiting()))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('message',e=>{if(e.data&&e.data.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.pathname.includes('/api/'))return;if(u.pathname.endsWith('.html')||u.pathname.endsWith('/neuroped/')||u.pathname==='/neuroped')e.respondWith(htmlFirst(e.request,u.pathname));else e.respondWith(cacheFirst(e.request))});
async function cacheFirst(req){const cached=await caches.match(req);if(cached)return cached;try{const res=await fetch(req);if(res&&res.ok){const c=await caches.open(CACHE_NAME);c.put(req,res.clone())}return res}catch{return new Response('',{status:408})}}
function addScript(html,src){return html.includes(src)?html:html.replace('</body>','<script src="'+src+'" defer></script></body>')}
function addScaleLayers(out){out=addScript(out,'./scales-featured-10.js');out=addScript(out,'./scales-453-authorial.js');out=addScript(out,'./scales-global-max.js');return out}
function patch(html,path){let out=html;if(/(filtro-escalas|mapa-escalas|instrumento|escalas)\.html/i.test(path)){out=addScaleLayers(out)}if(/(filtro-escalas|mapa-escalas|escalas)\.html/i.test(path))out=addScript(out,'./featured-10-panel.js');if(/filtro-escalas\.html/i.test(path))out=addScript(out,'./filtro-rank-pro.js');if(/mapa-escalas\.html/i.test(path))out=addScript(out,'./mapa-open-fix.js');if(/instrumento\.html/i.test(path))out=addScript(out,'./instrumento-453-loader.js');return out}
async function htmlFirst(req,path){const c=await caches.open(CACHE_NAME);try{const res=await fetch(req,{cache:'no-store'});if(res&&res.ok){let html=await res.clone().text();html=patch(html,path);const patched=new Response(html,{status:res.status,statusText:res.statusText,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'}});c.put(req,patched.clone());return patched}return res}catch{const cached=await c.match(req);return cached||c.match('./index.html')||new Response('NeuroPed offline',{status:503})}}
