import { AGE_BANDS, PHASES, type AgeBand } from "./protocol";

/** Operational aids, not new norms or diagnostic tasks. Quantities describe the kit only. */
export const MATERIALS = {
  device: { label: "Celular + suporte", quantity: "1 conjunto", detail: "Carregado, horizontal e fixo. Em gravação externa, use outro aparelho para ler o roteiro.", substitute: "Tablet institucional fixo com câmera e microfone." },
  mat: { label: "Colchonete firme", quantity: "1", detail: "No chão, limpo, plano e com cuidador ao alcance. Não usar mesa, cama ou superfície elevada.", substitute: "Tapete firme, limpo e antiderrapante." },
  target: { label: "Brinquedo para olhar e alcançar", quantity: "1", detail: "Grande, leve, de contraste visível; sem luz piscante, som alto ou partes destacáveis.", substitute: "Brinquedo familiar grande, seguro e higienizado." },
  blocks: { label: "Blocos grandes", quantity: "6", detail: "Leves e inteiros; adequados à idade. Separe só os pedidos na tarefa.", substitute: "Copos plásticos grandes e firmes para empilhar; registre a troca." },
  bowl: { label: "Recipiente largo", quantity: "1", detail: "Plástico, sem bordas cortantes; tampa fácil, sem risco de prender dedos.", substitute: "Pote grande que receba os blocos sem esforço." },
  cloth: { label: "Pano para esconder o brinquedo", quantity: "1", detail: "Somente sobre o objeto. Nunca cobrir o rosto ou a cabeça da criança.", substitute: "Fralda de pano limpa e pequena, segurada pelo adulto." },
  doll: { label: "Boneco", quantity: "1", detail: "Inteiro, com partes firmes, sem olhos, roupas ou acessórios pequenos destacáveis.", substitute: "Bichinho de brinquedo familiar e seguro." },
  spoon: { label: "Colher de brinquedo", quantity: "1", detail: "Grande, sem pontas. Brincadeira simbólica, sem oferecer alimento.", substitute: "Colher plástica grande e íntegra, apenas para brincar." },
  cup: { label: "Copo plástico vazio", quantity: "1", detail: "Grande, firme e sem rachaduras. Não utilizar vidro, líquido ou alimento.", substitute: "Caneca plástica leve, vazia e sem bordas cortantes." },
  car: { label: "Carrinho grande", quantity: "1", detail: "Rodas fixas, sem peças pequenas. Usado para escolha e comando simples.", substitute: "Outro brinquedo conhecido; use seu nome e registre a adaptação." },
  book: { label: "Livro com cenas simples", quantity: "1", detail: "Figuras claras de ações familiares, sem resposta escrita. Deixe uma página escolhida antes.", substitute: "Cartões de cenas do aplicativo, impressos antes da criança chegar." },
  paper: { label: "Folhas em branco", quantity: "3", detail: "Sem nome completo. Uma para modelos da aplicadora, outra para a criança e uma reserva. Nos escolares, prepare a frase da ficha em papel separado antes de iniciar.", substitute: "Papel branco firme, sem linhas ou figuras que induzam a resposta." },
  crayon: { label: "Giz de cera grosso", quantity: "2", detail: "Inteiro, adequado à idade, sem fragmentos pequenos. Não corrigir a pega.", substitute: "Lápis grosso adequado à idade, com supervisão." },
  pencil: { label: "Lápis", quantity: "1", detail: "Material habitual da criança; não trocar a mão nem corrigir preensão.", substitute: "Caneta ou recurso habitual; registrar a adaptação." },
  ball: { label: "Bola grande e macia", quantity: "1", detail: "Leve, sem partes rígidas. Distância curta; sem lançar em direção à face.", substitute: "Bola macia familiar. Sem substituição segura: omitir a tarefa." },
  chair: { label: "Cadeira estável", quantity: "1", detail: "Sem rodas, firme e adequada à altura. Apoios habituais não são retirados.", substitute: "Assento estável habitual. Nunca cadeira giratória." },
  path: { label: "Trajeto livre e duas marcas", quantity: "Cerca de 3 m, se disponível", detail: "Piso plano e antiderrapante, sem obstáculos. Marcas com fita bem aderida, sem relevos.", substitute: "Trajeto menor seguro; registrar distância/adaptação. Sem espaço: omitir marcha." },
} as const;
export type MaterialId = keyof typeof MATERIALS;
export interface KitItem { id: MaterialId; quantity?: string }
const kit = (...ids: MaterialId[]): KitItem[] => ids.map((id) => ({ id }));
export const KITS: Record<string, KitItem[]> = {
  m00: kit("device", "mat", "target"),
  m03: kit("device", "mat", "target"),
  m06: [...kit("device", "mat", "bowl"), { id: "target", quantity: "2" }],
  m09: [...kit("device", "mat", "target", "cloth"), { id: "blocks", quantity: "2" }],
  m12: [...kit("device", "mat", "cup", "doll", "book", "chair"), { id: "blocks", quantity: "2" }],
  m18: kit("device", "mat", "doll", "spoon", "car", "blocks", "crayon", "paper"),
  m24: kit("device", "doll", "cup", "spoon", "book", "ball", "crayon", "paper", "bowl", "blocks"),
  y03: kit("device", "doll", "cup", "spoon", "book", "paper", "crayon", "blocks", "ball"),
  y04: kit("device", "book", "paper", "pencil", "blocks", "ball"),
  y05: [...kit("device", "paper", "pencil", "path", "chair"), { id: "blocks", quantity: "5" }],
  y06: kit("device", "paper", "pencil", "path", "chair"),
  y09: kit("device", "paper", "pencil", "path", "chair"),
  y12: kit("device", "paper", "pencil", "path", "chair"),
};
export type Scene = "welcome" | "face" | "target" | "reach" | "mat" | "prone" | "hide" | "blocks" | "pretend" | "book" | "walk" | "rise" | "arms" | "nose" | "balance" | "ball" | "draw" | "hands" | "words" | "plan" | "rule" | "finish" | "frame-face" | "frame-body" | "frame-hands" | "picture-play" | "picture-eat" | "picture-cat";
export interface PracticalTask {
  id: string; phase: number; title: string; say: string; steps: readonly string[];
  record: string; scene: Scene; seconds: number; materials: readonly MaterialId[];
  model?: boolean; minMonths?: number; prone?: boolean; walking?: boolean;
}
type TaskSpec = Omit<PracticalTask, "id" | "phase">;
function task(title: string, say: string, steps: readonly string[], record: string, scene: Scene, seconds: number, materials: readonly MaterialId[] = [], extra: Partial<TaskSpec> = {}): TaskSpec {
  return { title, say, steps, record, scene, seconds, materials, ...extra };
}
const arrival = task("Observe antes de pedir", "Não dê comandos ainda. Deixe chegar e se acomodar.", ["Posicione a câmera antes da interação.", "Cuidador permanece perto; preserve apoios e objeto de conforto.", "Observe a iniciativa sem corrigir postura ou comportamento."], "Descreva posição, movimentação e iniciativa visíveis; não escreva ‘normal’ sem examinar.", "welcome", 30);
const caregiver = task("Convide o cuidador a interagir", "Converse e sorria como costuma fazer; depois espere a resposta.", ["Fale perto, no volume habitual.", "Faça pausas para o bebê responder.", "Sem susto, cócega ou exigência de olhar nos olhos."], "Registre o que ocorreu: orientação, som, sorriso, choro e ajuda para se acalmar, quando presentes.", "face", 90);
const look = task("Apresente o brinquedo devagar", "Mostre o brinquedo na frente e mova devagar para cada lado.", ["Comece parado na linha média.", "Mova em pequeno arco, sem encostar no rosto.", "Se perder interesse, não persiga o olhar nem sacuda o brinquedo."], "Diga para qual lado orientou olhos/cabeça; não conclua visão ou audição normais.", "target", 70, ["target"]);
const reach = task("Ofereça ao alcance das mãos", "Agora o brinquedo fica ao alcance; deixe tentar.", ["Aproxime sem colocar à força na mão.", "Ofereça de um lado e depois do outro.", "Não segure um braço para forçar o uso do outro."], "Registre alcance, mão utilizada e ajuda; não inferir força segmentar.", "reach", 50, ["target"]);
const prone = task("Breve posição de bruços, se liberada", "Cuidador, coloque de bruços apenas se autorizado e confortável.", ["Somente acordado, em superfície firme no chão e com supervisão contínua.", "Observe por 15–30 segundos, sem pressionar ou retirar apoio.", "Interrompa prontamente diante de desconforto."], "Descreva apenas cabeça, apoios e movimentos visíveis. Se não autorizado, registre a omissão.", "prone", 40, ["mat"], { prone: true });
const babyPosition = task("Filme a posição habitual segura", "Mantenha os apoios que já usa. Deixe movimentar espontaneamente.", ["Cuidador posiciona no colo ou no chão firme.", "Mostre cabeça, tronco e os quatro membros.", "Não tracionar pelos braços nem provocar rolar, sentar ou cair."], "Descreva apoios, transições e movimentos efetivamente observados.", "mat", 70, ["mat"]);
const naturalCall = task("Faça até duas chamadas naturais", "Cuidador, chame como chama em casa, em momentos separados.", ["Não gritar ou tocar para obter orientação.", "Aguarde a resposta em cada oportunidade.", "Não repetir em sequência nem exigir olhar nos olhos."], "Anote oportunidades e resposta observada. Não demonstrar aqui não prova perda auditiva ou autismo.", "face", 40);
const choice = task("Ofereça uma escolha", "Com qual você quer brincar?", ["Ofereça dois objetos seguros visíveis.", "Aceite gesto, palavra, olhar ou recurso de comunicação habitual.", "Não mantenha o objeto fora de alcance para provocar frustração."], "Descreva como escolheu, pediu, mostrou ou compartilhou e para quem.", "reach", 50);
const hide = task("Esconda só parte do brinquedo", "Olha onde o brinquedo ficou.", ["Diante da criança, cubra parcialmente o brinquedo com o pano.", "Aguarde busca sem apontar a resposta.", "Se houver frustração, retire o pano. Nunca cobrir o rosto."], "Registre se procurou, olhou ou pediu ajuda; não extrapole capacidade cognitiva.", "hide", 60, ["target", "cloth"]);
const blocks = task("Ofereça os dois blocos", "Você pode brincar com estes blocos.", ["Entregue um e depois outro.", "Observe uso das mãos e transferência.", "Deixe explorar livremente; não modele uma construção nesta tarefa."], "Descreva manipulação, estratégia e qualquer ajuda adicional, sem nota.", "blocks", 70, ["blocks"]);
const container = task("Convide a colocar no recipiente", "Coloque o bloco aqui.", ["Deixe recipiente e bloco grandes visíveis.", "Use gesto apenas se previsto ou após registrar a necessidade.", "Observe sem conduzir a mão da criança."], "Registre compreensão, execução e ajuda separadamente.", "blocks", 50, ["blocks", "cup"]);
const pretend = task("Brinque com o boneco", "O bebê está com fome; vamos brincar?", ["Disponibilize boneco e colher grandes, sem alimento.", "Espere iniciativa; não narre a resposta desejada.", "Se necessário, modele uma ação e registre a imitação."], "Descreva a ação espontânea ou após modelo; não fechar diagnóstico pela ausência de faz de conta.", "pretend", 60, ["doll", "spoon"]);
const simpleCommand = task("Dê um comando sem apontar", "Me dê o carrinho.", ["Deixe o carrinho ao alcance e não aponte inicialmente.", "Aguarde, repita uma vez se necessário.", "Acrescente gesto somente depois e registre a ajuda."], "Anote o que entregou e em qual apresentação; não assumir desatenção.", "reach", 60, ["car"]);
const walkSmall = task("Observe o deslocamento habitual", "Leve este brinquedo para seu cuidador.", ["Escolha trajeto curto e plano.", "Mantenha apoio habitual e cuidador próximo.", "Não puxar pelos braços; quem não anda é observado no modo de deslocamento habitual."], "Descreva apoio, trajeto e virada, sem concluir ‘marcha normal’ a partir da amostra.", "walk", 70);
const pick = task("Convide a pegar o brinquedo", "Pode pegar o brinquedo no chão?", ["Coloque objeto grande perto, sem provocar desequilíbrio.", "Deixe abaixar e levantar do seu jeito, se habitual e seguro.", "Não impedir apoio das mãos. Dor ou insegurança: omitir."], "Descreva estratégia e apoios; não rotular fraqueza a partir de uma tentativa.", "rise", 40);
const scribble = task("Deixe rabiscar", "Pode desenhar do seu jeito.", ["Ofereça giz grosso e folha em branco.", "Filme as duas mãos e a folha.", "Não corrija pega, mão ou traçado."], "Descreva marcas, manipulação e apoio da outra mão, sem interpretação projetiva.", "draw", 70, ["paper", "crayon"]);
const finishYoung = task("Avise a transição e encerre", "Terminamos. Vamos guardar os materiais sem retirar seu objeto de conforto.", ["Avise antes de trocar a atividade.", "Ofereça ajuda sem confronto; não retirar objeto de conforto.", "Encerre antes se houver cansaço ou recusa persistente."], "Registre pedido, recusa, reação à transição e ajuda para se reorganizar, se observados.", "finish", 60);
const ballKick = task("Convide a chutar bola macia", "Pode chutar a bola para mim?", ["Bola parada próxima e piso seguro.", "Cuidador protege sem executar o movimento.", "Omitir se não houver marcha estável ou houver dor."], "Descreva como aproximou, apoiou e chutou; não atribua escore.", "ball", 35, ["ball"], { walking: true });
const jump = task("Pequeno salto com dois pés", "Vamos dar um pulinho aqui, se for confortável?", ["Somente a partir de 30 meses, se seguro e habitual.", "Cuidador ao alcance, sem puxar ou elevar a criança.", "Uma oportunidade; omitir se houver insegurança."], "Registre o movimento efetivo ou o motivo da omissão.", "balance", 20, [], { minMonths: 30, walking: true });
const talk = task("Converse sem sugerir a resposta", "Como tem se sentido? O que está mais difícil na escola ou em casa?", ["Use linguagem compatível com idade e comunicação.", "Faça uma pergunta por vez e deixe responder.", "Conteúdo sensível: pare a gravação e chame o médico para conversa reservada."], "Separe o que relata do que você observa; expressão tranquila não exclui sofrimento.", "face", 90);
const encode = task("Apresente as três palavras", "Guarde estas palavras para me contar depois: casa, gato, pão. Repita para mim.", ["No máximo duas apresentações, em voz habitual.", "Marque o registro inicial quando conferir a repetição.", "Anote literalmente o que repetiu; não dê treino extra nem mostre a tela."], "Sem registro inicial documentado, evocação não isola retenção. Não dar nota.", "words", 40);
const recall = task("Peça as palavras sem pistas", "Quais eram as três palavras que pedi para guardar?", ["Marque o momento da evocação.", "Aguarde sem mostrar imagens, completar sílabas ou dar categorias.", "Registre a resposta literal e eventuais interferências."], "Intervalo é o marcado na aplicação; não é timestamp conferido do vídeo.", "words", 30);
const rule = task("Experimente uma regra simples", "Quando eu disser SOL, bata uma vez na mesa. Quando disser LUA, deixe as mãos paradas.", ["Uma prática de cada. Se não compreender, omita.", "Diga SOL–SOL–LUA–SOL–LUA–LUA–SOL–LUA, com 2–3 segundos entre eles.", "Não somar erros, acelerar, repetir para treinar ou mostrar esta tela à criança."], "Descreva a compreensão e o que fez; erros não diagnosticam TDAH.", "rule", 45);
const school = task("Amostra de leitura e escrita", "Leia esta frase e me diga o que aconteceu. Depois escreva uma frase do seu jeito.", ["Antes da chegada, escreva ou imprima ‘O gato dorme na cadeira’ em folha separada; mostre só essa frase, se compatível com o ensino recebido.", "Até 20 segundos de leitura; aceite não saber e não constranja.", "Sem alfabetização compatível, registre não aplicado e observe grafismo disponível."], "Anote o texto utilizado, escolaridade e resposta; não estimar inteligência ou dislexia.", "book", 75, ["paper", "pencil"]);
const hands = task("Observe os movimentos das mãos", "Toque o polegar nos outros dedos, uma mão de cada vez.", ["Mostre uma vez, devagar.", "Observe uma mão e depois a outra.", "Sem exigir velocidade nem guiar fisicamente os dedos."], "O modelo é parte da proposta. Registre apenas ajuda adicional e execução observável.", "hands", 35, [], { model: true });
const motor: TaskSpec[] = [
  task("Alvo e sorriso", "Acompanhe a ponta do lápis devagar. Depois, pode sorrir?", ["Pequeno arco horizontal e vertical, sem luz.", "Não tocar olhos nem segurar cabeça.", "Não insistir diante de recusa."], "Descreva movimentos visíveis; não excluir alteração de nervos cranianos.", "target", 20, ["pencil"]),
  task("Caminhar, virar e voltar", "Caminhe até a marca, vire e volte no seu ritmo.", ["Cerca de 3 metros, se o espaço permitir.", "Piso livre, cuidador próximo e apoios habituais.", "Sem marcha estável, dor ou espaço seguro: omita."], "Descreva trajeto, base aparente, passos, virada e apoio, quando visíveis.", "walk", 40, ["path"], { walking: true }),
  task("Levantar do seu jeito", "Sente no chão e levante do seu jeito, somente se isso for habitual e confortável.", ["Cuidador próximo, sem induzir queda.", "Alternativa segura: levantar da cadeira estável.", "Registre a alternativa; não impeça apoio das mãos."], "Descreva apoio e estratégia; não conclua déficit de força só pelo vídeo.", "rise", 20, ["chair"]),
  task("Braços à frente", "Estique os braços à frente com as palmas para cima.", ["Pode permanecer sentado, com apoio habitual.", "Até 10 segundos, olhos abertos.", "Sem empurrar, resistir ou corrigir assimetrias."], "Registre posição e movimentos observados; isso não mede força 5/5.", "arms", 15),
  task("Dedo ao nariz e ao alvo", "Toque o nariz com este dedo e depois o meu dedo.", ["Três movimentos lentos de cada lado.", "Alvo ao alcance, sem tocar os olhos.", "Modelo se necessário: documente; não exigir rapidez."], "Descreva trajetória, correções e ajuda, sem diagnosticar ataxia por uma resposta.", "nose", 25),
  task("Um pé, depois o outro", "Fique em um pé um pouquinho; depois no outro.", ["Somente com marcha estável e proteção próxima.", "Até 5 segundos de cada lado, olhos abertos.", "Não soltar apoio, empurrar ou prolongar tentativa."], "Anote tempo observado se medido, apoio e motivo de interrupção; sem norma etária própria.", "balance", 20, [], { walking: true }),
  task("Permita sentar", "Pode sentar. Vamos para a próxima atividade.", ["Ajude apenas como habitualmente necessário.", "Registre o que não foi aplicado por segurança.", "Não acrescente testes."], "Omissão não significa incapacidade.", "finish", 10, ["chair"]),
];
function compile(band: AgeBand, groups: TaskSpec[][]): PracticalTask[] {
  const available = KITS[band.id].map((item) => item.id);
  const toys = (["car", "blocks", "doll", "target"] as MaterialId[]).filter((id) => available.includes(id));
  return groups.flatMap((group, phase) => group.map((item, index) => ({
    ...item, id: `${band.id}-${phase}-${index}`, phase,
    materials: item.materials.length ? item.materials
      : item.title === choice.title ? toys.slice(0, 2)
      : item.title === walkSmall.title || item.title === pick.title ? toys.slice(0, 1)
      : [],
  })));
}
function specs(id: string): TaskSpec[][] {
  if (id === "m00") return [[arrival], [caregiver], [look], [babyPosition, prone], [task("Observe mãos livres", "Deixe as mãos se moverem espontaneamente.", ["Mantenha posição confortável.", "Não abrir os dedos à força.", "Sem objetos pequenos."], "Descreva abertura e movimentos para a linha média, se presentes.", "hands", 60)], [finishYoung]];
  if (id === "m03") return [[arrival], [caregiver], [look, reach], [babyPosition, prone], [task("Ofereça e observe segurar", "Ofereça o brinquedo a uma mão e depois à outra.", ["Não force abertura dos dedos.", "Observe se sustenta e explora.", "Não exigir transferência entre mãos."], "Descreva manutenção do objeto e ajuda, sem inferir tônus.", "reach", 90, ["target"])], [finishYoung]];
  if (id === "m06") return [[arrival], [caregiver], [look, reach], [babyPosition, prone], [task("Dois brinquedos, duas mãos", "Ofereça um brinquedo e depois o outro.", ["Objetos grandes e leves.", "Observe exploração e eventual transferência.", "Aproxime recipiente largo, sem executar pela criança."], "Descreva uso das mãos e apoio necessário.", "reach", 90, ["target", "bowl"])], [finishYoung]];
  if (id === "m09") return [[arrival], [naturalCall, choice], [hide], [babyPosition], [{ ...blocks, title: "Bater dois blocos", say: "Olhe como faço com estes dois blocos.", steps: ["Entregue um bloco grande e depois outro.", "Mostre uma vez bater os dois blocos entre si.", "Aguarde sem conduzir as mãos; registre a resposta ao modelo."], model: true }], [finishYoung]];
  if (id === "m12") return [[arrival], [naturalCall, choice], [container, task("Explore uma figura e o boneco", "O que tem aqui? Vamos brincar?", ["Abra figura familiar no livro.", "Disponibilize copo e boneco.", "Observe iniciativa sem exigir nomeação."], "Descreva palavras, gestos e uso dos objetos; diferencie 12 de 15 meses.", "pretend", 60, ["book", "cup", "doll"])], [walkSmall, pick], [{ ...blocks, title: "Empilhar dois blocos", say: "Vamos colocar um bloco em cima do outro?", steps: ["Deixe dois blocos grandes ao alcance.", "Aguarde uma tentativa; modele uma vez somente se necessário.", "Registre se houve modelo, sem conduzir as mãos."] }, task("Folheie o livro", "Vamos olhar o livro?", ["Ofereça livro cartonado.", "Permita virar a página do seu jeito.", "Não conduza as mãos."], "Descreva manipulação e apoio, se observados.", "book", 40, ["book"])], [finishYoung]];
  if (id === "m18") return [[arrival], [naturalCall, choice], [simpleCommand, pretend], [walkSmall, pick], [scribble, { ...blocks, seconds: 40 }], [finishYoung]];
  if (id === "m24") return [[arrival], [choice, { ...pretend, seconds: 40 }], [task("Peça partes do corpo e figura", "Mostre o nariz. Agora a mão. Onde está o gato nesta figura?", ["Use uma figura escolhida antes.", "Um pedido por vez.", "Sem apontar a resposta inicialmente."], "Descreva o que apontou e a ajuda; não somar pontos.", "book", 65, ["book"]), task("Comando de dois passos, aos 30 meses", "Pegue o bloco e coloque no copo.", ["Somente a partir de 30 meses.", "Dê a instrução completa, sem gesto inicial.", "Uma repetição, se necessária; registre."], "Descreva cada etapa realizada e a ajuda.", "blocks", 45, ["blocks", "cup"], { minMonths: 30 })], [{ ...walkSmall, seconds: 55 }, ballKick, jump], [scribble, task("Abrir o recipiente", "Pode abrir este pote?", ["Tampa fácil, sem risco para dedos.", "Deixe usar as duas mãos.", "Não corrigir estratégia."], "Descreva coordenação das mãos e apoio.", "hands", 40, ["bowl"])], [finishYoung]];
  if (id === "y03") return [[arrival], [{ ...talk, say: "Do que você gosta de brincar? O que deixa você chateado?" }], [task("Conte o que vê na figura", "O que está acontecendo aqui?", ["Mostre uma cena simples sem legenda.", "Aguarde fala, gesto ou comunicação habitual.", "Não nomeie a ação antes da resposta."], "Registre palavras ou gestos, não um rótulo de linguagem.", "book", 45, ["book"]), { ...pretend, say: "O bebê vai comer e depois dormir; vamos brincar?", seconds: 40 }, task("Duas ações familiares", "Pegue o copo e entregue ao cuidador.", ["Deixe o copo vazio ao alcance.", "Dê as duas etapas sem apontar inicialmente.", "Repita uma vez se necessário e registre ajuda."], "Registre cada etapa realizada; não inferir desatenção.", "plan", 30, ["cup"])], [walkSmall, pick, ballKick], [task("Copie um círculo após o modelo", "Faça um parecido com este.", ["Desenhe um círculo na sua folha.", "Ofereça outra folha para a criança.", "Não corrigir pega nem contorno."], "O modelo integra a tarefa. Descreva traçado; não interpretar emoção ou inteligência.", "draw", 70, ["paper", "crayon"], { model: true }), { ...blocks, seconds: 40 }], [task("Duas trocas de brinquedo", "Agora vai para você; depois para mim.", ["Faça duas trocas simples com bola ou brinquedo.", "Sem tirar objeto de conforto.", "Avise que vai terminar."], "Registre participação, recusa e ajuda.", "finish", 60, ["ball"])]];
  if (id === "y04") return [[arrival], [{ ...talk, say: "Conte uma coisa que aconteceu hoje. Teve algo que deixou você chateado?" }], [task("Cena e utilidade", "O que acontece na figura? Para que serve um guarda-chuva?", ["Uma pergunta por vez.", "Não completar a frase.", "Aceite respostas plausíveis e recursos habituais."], "Registre resposta literal e organização da fala.", "book", 65, ["book"]), task("Separe objetos parecidos", "Coloque juntos os que têm a mesma cor.", ["Use quatro blocos grandes com uma diferença visível.", "Sem organizar pela criança.", "Mude o critério somente se compreendeu o primeiro e houver tempo."], "Descreva critério usado e ajuda, sem escore.", "blocks", 50, ["blocks"])], [{ ...walkSmall, seconds: 55 }, pick, task("Receba a bola macia", "Vou jogar a bola devagar para você pegar.", ["Duas tentativas de pequena distância.", "Lance suavemente na direção do tronco, nunca do rosto.", "Não forçar se recusar ou houver insegurança."], "Descreva tentativa e estratégia; duas tentativas não medem desempenho habitual.", "ball", 40, ["ball"])], [task("Desenho de pessoa", "Desenhe uma pessoa.", ["Folha em branco.", "Sem desenhar pela criança nem pedir partes específicas.", "Não interpretar conteúdo emocional."], "Descreva produção livre e ajuda; não estimar inteligência.", "draw", 45, ["paper", "pencil"]), ...["círculo", "cruz"].map((forma) => task(`Cópia de ${forma}`, "Faça um parecido com este.", [ `Modele um ${forma} na folha da aplicadora.`, "Ofereça outra folha.", "Não corrigir pega ou traçado."], "O modelo integra a tarefa. Cópia de cruz é sondagem, não corte diagnóstico.", "draw", 30, ["paper", "pencil"], { model: true }))], [finishYoung]];
  if (id === "y05") return [[arrival], [{ ...talk, say: "O que foi legal nos últimos dias? Alguma coisa atrapalha suas brincadeiras ou seu sono?" }], [task("História breve", "Um gato ficou preso numa árvore. Uma pessoa trouxe uma escada e ajudou o gato a descer. O que aconteceu? Como ele desceu?", ["Conte uma vez com voz habitual.", "Não mostre desenho com a resposta.", "Aguarde e registre a resposta literal."], "Descreva compreensão e sequência, não inferir inteligência.", "words", 70), task("Conte objetos", "Conte estes blocos. Você quer continuar contando até dez?", ["Coloque cinco blocos na mesa.", "Não apontar ou contar junto.", "Continuar até dez apenas se confortável."], "Registre a sequência e ajuda; não somar pontos.", "blocks", 45, ["blocks"])], motor, [task("Letras conhecidas", "Escreva algumas letras que conhece.", ["Não pedir nome completo nem exigir leitura.", "Sem fornecer letras para copiar.", "Não corrigir pega ou traçado."], "Descreva produção e ajuda, sem interpretar inteligência.", "draw", 45, ["paper", "pencil"]), ...["círculo", "quadrado"].map((forma) => task(`Cópia de ${forma}`, "Faça um parecido com este.", [`Modele um ${forma} na sua folha.`, "Ofereça outra folha.", "Não corrigir a estratégia."], "Modelo faz parte da proposta; quadrado é sondagem sem ponto de corte.", "draw", 30, ["paper", "pencil"], { model: true }))], [{ ...rule, steps: ["Uma prática de cada, somente se compreender.", "Use apenas SOL–LUA–SOL–LUA, com 2–3 segundos entre eles.", "Não somar pontos; avise o encerramento."], seconds: 60 }]];
  const command = task("Dê uma instrução em etapas", id === "y06" ? "Pegue o papel e coloque o lápis em cima dele." : "Toque na mesa, vire a folha e entregue o lápis.", ["Deixe papel e lápis ao alcance.", "Diga toda a instrução sem apontar inicialmente.", "Uma repetição, se necessária; registre cada etapa."], "Anote as ações e apresentações; não presumir desatenção.", "plan", 35, ["paper", "pencil"]);
  const planning = task("Peça um plano em voz alta", id === "y12" ? "Como dividiria três tarefas escolares para terminar hoje? Em que bicicleta e ônibus se parecem?" : "Como você organizaria a mochila para amanhã?", ["Aceite mais de uma resposta plausível.", "Não oferecer a sequência pronta.", "Respeite contexto e oportunidades de aprendizagem."], "Registre a estratégia explicada, sem nota de função executiva ou QI.", "plan", id === "y12" ? 75 : 40);
  const manual = id === "y06" ? hands : { ...hands, say: "Alterne palma e dorso na mesa, como mostrei, uma mão por vez.", steps: ["Um modelo lento faz parte da proposta.", "Cerca de 5 segundos de cada lado.", "Não exigir velocidade nem conduzir a mão."] };
  return [[arrival], [id === "y12" ? { ...talk, say: "Você sabe por que veio? Nas últimas duas semanas, como ficaram humor, energia e interesse? O que atrapalha sua rotina?" } : talk], id === "y12" ? [encode, planning] : [encode, command, id === "y09" ? planning : task("Conte um acontecimento", "O que você fez antes de chegar aqui?", ["Uma pergunta breve.", "Não completar detalhes.", "Não solicitar nomes ou endereço."], "Registre conteúdo e sequência, sem diagnóstico.", "face", 40)], motor, [id === "y12" ? { ...school, say: "Escreva uma frase sobre algo de que gosta e me conte o que escreveu.", steps: ["Papel em branco, sem dados pessoais.", "Recurso de escrita habitual.", "Pode responder oralmente se a escrita não for acessível; registre a adaptação."] } : id === "y09" ? { ...school, steps: ["Antes da chegada, prepare as frases ‘O gato dorme na cadeira. Quando acorda, vai brincar com a bola.’ em folha separada.", "Mostre apenas o texto, se compatível com a escolarização; peça que explique o sentido.", "Depois, uma frase própria; até 75 segundos no conjunto, sem constranger ou corrigir."] } : school, manual], [recall, rule]];
}
export const PRACTICAL_TASKS: Readonly<Record<string, PracticalTask[]>> = Object.fromEntries(AGE_BANDS.map((band) => [band.id, compile(band, specs(band.id))]));
export function taskOmission(task: PracticalTask, months: number, proneAllowed: boolean): string | null {
  if (task.minMonths !== undefined && months < task.minMonths) return `Não aplicar antes de ${task.minMonths} meses na idade utilizada.`;
  if (task.prone && !proneAllowed) return "Sem autorização para prono: observe somente a posição habitual segura.";
  return null;
}
export function getTaskBudget(bandId: string, phase: number): number {
  return (PRACTICAL_TASKS[bandId] ?? []).filter((task) => task.phase === phase).reduce((sum, task) => sum + task.seconds, 0);
}
export function validatePracticalCoverage(): string[] {
  const errors: string[] = [];
  for (const band of AGE_BANDS) {
    const tasks = PRACTICAL_TASKS[band.id] ?? [];
    if (!KITS[band.id]?.length) errors.push(`${band.id}: missing kit`);
    const supplied = new Set(KITS[band.id]?.map((item) => item.id));
    for (const item of tasks) for (const material of item.materials) if (!supplied.has(material)) errors.push(`${item.id}: missing ${material}`);
    PHASES.forEach((phase, index) => {
      if (!tasks.some((task) => task.phase === index)) errors.push(`${band.id}: missing phase ${index}`);
      if (getTaskBudget(band.id, index) > phase.end - phase.start) errors.push(`${band.id}: phase ${index} exceeds budget`);
    });
  }
  return errors;
}
