import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read=(p)=>readFileSync(new URL(`../../${p}`,import.meta.url),"utf8");
const op=read("functions/api/operations/_core.ts");
assert.doesNotMatch(op,/env\.NEUROPED_JWT_SECRET/);
assert.doesNotMatch(op,/OperationsEnv[\s\S]{0,220}NEUROPED_JWT_SECRET/);
assert.match(op,/OPERATIONAL_DATA_KEY_K1/);
assert.match(op,/v2\.\$\{keyId\}/);
const seed=read("db/seed.d1.sql");
assert.doesNotMatch(seed,/INSERT\s+INTO\s+(patients_demo|consultations_demo|scale_results_demo|documents_demo|memory_notes)/i);
const patients=read("functions/api/patients/index.ts");
assert.match(patients,/name='?\[encrypted\]'?|\[encrypted\]/);
assert.match(patients,/replaceBlindTokensStatements/);
const consultations=read("functions/api/consultations/index.ts");
assert.match(consultations,/objective, assessment, plan/);
assert.match(consultations,/NULL, NULL, NULL/);
const docs=read("functions/api/documents/index.ts");
assert.match(docs,/type.*encrypted/);
const scales=read("functions/api/scales/results.ts");
assert.match(scales,/scale_id.*encrypted/);
const memory=read("functions/api/memory/search.ts");
assert.doesNotMatch(memory,/memory_notes_fts/);
assert.match(memory,/searchEncryptedEntityIds/);
const clinical=read("functions/api/clinical-core/index.ts");
assert.match(clinical,/provenance_source.*encrypted/);
const conecta=read("functions/api/conecta/index.ts");
assert.match(conecta,/category.*encrypted/);
const migration=read("functions/api/admin/crypto-migration.ts");
for(const marker of ["residualPlaintext","decryptFailures","missingSearchIndexes","readyForStrict"]) assert.match(migration,new RegExp(marker));
console.log("✓ persistência clínica D1 não reintroduz payload clínico em texto aberto nem deriva chave operacional do JWT");
