import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const read = (relative) => fs.readFileSync(path.join(root, relative), "utf8");
const migration = read("db/migrations/0016_saas_control_plane_hardening.sql");
const modules = read("shared/saas-modules.ts");
const controlPlane = read("functions/api/saas/modules.ts");
const patients = read("functions/api/live/patients/index.ts");
const patientDetail = read("functions/api/live/patients/[id].ts");
const search = read("functions/api/live/patients/_search.ts");
const tenantCore = read("functions/api/tenant/_core.ts");
const consolePage = read("client/src/pages/saas-central.tsx");
const privacyApi = read("functions/api/saas/privacy.ts");
const backupApi = read("functions/api/saas/backup-evidence.ts");
const readinessApi = read("functions/api/saas/readiness.ts");
const keyringApi = read("functions/api/saas/keyring.ts");
const inviteCreate = read("functions/api/tenants/[id]/invites.ts");
const inviteAccept = read("functions/api/tenants/invites/accept.ts");
const fileRoutes = read("server/routes/files.ts");
const privacyMigration = read("db/migrations/0018_saas_privacy_governance.sql");
const inviteMigration = read("db/migrations/0017_saas_membership_invites.sql");
const integrationsMigration = read("db/migrations/0019_saas_integrations_control.sql");
const integrationsApi = read("functions/api/saas/integrations.ts");
const runbook = read("docs/saas-production-runbook.md");
const operational = read("shared/saas-operational.ts");

assert.match(modules, /SAAS_MODULE_IDS = \[/);
assert.equal((modules.match(/^  "[a-z-]+",$/gm) ?? []).length, 20, "o catálogo precisa conter exatamente 20 módulos");
assert.match(migration, /CREATE TABLE IF NOT EXISTS saas_module_settings/);
assert.match(migration, /UNIQUE \(clinic_id, module_id\)/);
assert.match(migration, /SAAS_MODULE_SETTING_SCOPE_IMMUTABLE/);
assert.match(migration, /SAAS_MODULE_SETTING_VERSION_CONFLICT/);
assert.match(migration, /CREATE TABLE IF NOT EXISTS live_patient_search_tokens/);
assert.match(migration, /LIVE_PATIENT_SEARCH_TOKEN_TENANT_MISMATCH/);
assert.match(migration, /idx_live_patients_clinic_status_created_id/);
assert.match(controlPlane, /getClinicMembership/);
assert.match(controlPlane, /membershipCanManage/);
assert.match(controlPlane, /requireBillingEntitlement\(db, user\.id, clinicId, "admin"\)/);
assert.match(controlPlane, /WHERE saas_module_settings\.version = \?/);
assert.match(controlPlane, /prepareSaasAudit/);
assert.match(patients, /live_patient_search_tokens/);
assert.match(patients, /nextCursor/);
assert.match(patients, /ORDER BY p\.created_at DESC, p\.id DESC/);
assert.match(patients, /hasUsefulSearchValue/);
assert.match(patientDetail, /DELETE FROM live_patient_search_tokens/);
assert.match(patientDetail, /updated_at = \?/);
assert.match(search, /clinicalBlindIndex/);
assert.match(search, /patient-search/);
assert.match(tenantCore, /X-Content-Type-Options/);
assert.match(tenantCore, /no-store, max-age=0/);
assert.match(consolePage, /\/api\/saas\/modules/);
assert.match(consolePage, /toggleModule/);
assert.match(consolePage, /Nenhum tenant ativo/);
assert.match(consolePage, /\/api\/saas\/privacy/);
assert.match(consolePage, /\/api\/saas\/backup-evidence/);
assert.match(privacyApi, /subject_reference_hash/);
assert.match(privacyApi, /PRIVACY_REQUEST_TRANSITION_INVALID/);
assert.match(privacyApi, /RETENTION_POLICY_STALE/);
assert.match(backupApi, /snapshotDigestSha256/);
assert.match(backupApi, /RESTORE_TIMESTAMP_REQUIRED/);
assert.match(readinessApi, /readyForProduction/);
assert.match(keyringApi, /keyMaterialExposed: false/);
assert.match(inviteCreate, /tokenHash/);
assert.match(inviteCreate, /inviteEmailHash/);
assert.match(inviteAccept, /INVITE_EMAIL_MISMATCH/);
assert.match(inviteAccept, /SEAT_LIMIT_REACHED/);
assert.match(fileRoutes, /LEGACY_FILE_ROUTE_DISABLED_IN_LIVE/);
assert.match(privacyMigration, /SAAS_AUDIT_APPEND_ONLY/);
assert.match(privacyMigration, /saas_privacy_requests/);
assert.match(inviteMigration, /SAAS_INVITE_SCOPE_IMMUTABLE/);
assert.match(integrationsMigration, /saas_integration_connections/);
assert.match(integrationsMigration, /SAAS_INTEGRATION_SCOPE_IMMUTABLE/);
assert.match(integrationsMigration, /SAAS_INTEGRATION_VERSION_CONFLICT/);
assert.match(integrationsApi, /operationalBlindHash/);
assert.match(integrationsApi, /SANDBOX_REQUIRED/);
assert.match(integrationsApi, /CLINICAL_SCOPE_REQUIRED/);
assert.match(consolePage, /\/api\/saas\/integrations/);
assert.match(consolePage, /createInvite/);
assert.match(consolePage, /transitionPrivacyRequest/);
assert.match(runbook, /readiness/);
assert.match(runbook, /Não é certificação LGPD/);
assert.match(operational, /INTEGRATION_IDS = \[/);
assert.match(operational, /clinical\.read/);
assert.match(operational, /requiresSandbox/);
assert.match(operational, /isPrivacyRequestStatus/);
console.log("[saas-production-hardening] ✓ contratos de tenant, LGPD, blind search, concorrência, continuidade, convites, integrações e fail-closed aprovados");
