import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const read = (relative) => fs.readFileSync(path.join(root, relative), "utf8");
const migration = read("db/migrations/0016_saas_control_plane_hardening.sql");
const modules = read("shared/saas-modules.ts");
const controlPlane = read("functions/api/saas/modules.ts");
const patients = read("functions/api/live/patients/index.ts");
const patientDetail = read("functions/api/live/patients/[id].ts");
const search = read("functions/api/live/patients/_search.ts");
const tenantCore = read("functions/api/tenant/_core.ts");
const consolePage = read("client/src/pages/saas-central.tsx");
const privacyApi = read("functions/api/saas/privacy.ts");
const backupApi = read("functions/api/saas/backup-evidence.ts");
const readinessApi = read("functions/api/saas/readiness.ts");
const keyringApi = read("functions/api/saas/keyring.ts");
const diagnosticsApi = read("functions/api/saas/production-diagnostics.ts");
const readinessHelper = read("functions/api/saas/_readiness.ts");
const inviteCreate = read("functions/api/tenants/[id]/invites.ts");
const inviteAccept = read("functions/api/tenants/invites/accept.ts");
const fileRoutes = read("server/routes/files.ts");
const privacyMigration = read("db/migrations/0018_saas_privacy_governance.sql");
const inviteMigration = read("db/migrations/0017_saas_membership_invites.sql");
const integrationsMigration = read("db/migrations/0019_saas_integrations_control.sql");
const idempotencyMigration = read("db/migrations/0020_saas_integration_idempotency.sql");
const backupEvidenceMigration = read("db/migrations/0021_saas_backup_evidence_append_only.sql");
const webhookMigration = read("db/migrations/0022_saas_webhook_deliveries.sql");
const webhookApi = read("functions/api/saas/webhooks.ts");
const observabilityApi = read("functions/api/saas/observability.ts");
const incidentsApi = read("functions/api/saas/incidents.ts");
const incidentMigration = read("db/migrations/0023_saas_incident_events.sql");
const rateLimitMigration = read("db/migrations/0024_saas_rate_limit_buckets.sql");
const rateLimitHelper = read("functions/api/saas/_rate-limit.ts");
const integrationsApi = read("functions/api/saas/integrations.ts");
const runbook = read("docs/saas-production-runbook.md");
const operational = read("shared/saas-operational.ts");
const productionGates = read(".github/workflows/saas-production-gates.yml");
const migrationManifest = read("scripts/guards/saas-migration-manifest.mjs");
const migrationRollback = read("docs/saas-migration-rollback.md");
const stagingEvidence = read("scripts/guards/saas-staging-evidence.mjs");

assert.match(modules, /SAAS_MODULE_IDS = \[/);
assert.equal((modules.match(/^  "[a-z-]+",$/gm) ?? []).length, 20, "o catálogo precisa conter exatamente 20 módulos");
assert.match(migration, /CREATE TABLE IF NOT EXISTS saas_module_settings/);
assert.match(migration, /UNIQUE \(clinic_id, module_id\)/);
assert.match(migration, /SAAS_MODULE_SETTING_SCOPE_IMMUTABLE/);
assert.match(migration, /SAAS_MODULE_SETTING_VERSION_CONFLICT/);
assert.match(migration, /CREATE TABLE IF NOT EXISTS live_patient_search_tokens/);
assert.match(migration, /LIVE_PATIENT_SEARCH_TOKEN_TENANT_MISMATCH/);
assert.match(migration, /idx_live_patients_clinic_status_created_id/);
assert.match(controlPlane, /getClinicMembership/);
assert.match(controlPlane, /membershipCanManage/);
assert.match(controlPlane, /requireBillingEntitlement\(db, user\.id, clinicId, "admin"\)/);
assert.match(controlPlane, /WHERE saas_module_settings\.version = \?/);
assert.match(controlPlane, /prepareSaasAudit/);
assert.match(patients, /live_patient_search_tokens/);
assert.match(patients, /nextCursor/);
assert.match(patients, /ORDER BY p\.created_at DESC, p\.id DESC/);
assert.match(patients, /hasUsefulSearchValue/);
assert.match(patientDetail, /DELETE FROM live_patient_search_tokens/);
assert.match(patientDetail, /updated_at = \?/);
assert.match(search, /clinicalBlindIndex/);
assert.match(search, /patient-search/);
assert.match(tenantCore, /X-Content-Type-Options/);
assert.match(tenantCore, /no-store, max-age=0/);
assert.match(tenantCore, /operationalCryptoReady/);
assert.match(tenantCore, /clinicalSecrets/);
assert.match(consolePage, /\/api\/saas\/modules/);
assert.match(consolePage, /toggleModule/);
assert.match(consolePage, /Nenhum tenant ativo/);
assert.match(consolePage, /\/api\/saas\/privacy/);
assert.match(consolePage, /\/api\/saas\/keyring/);
assert.match(consolePage, /\/api\/saas\/readiness/);
assert.match(consolePage, /\/api\/saas\/backup-evidence/);
assert.match(privacyApi, /subject_reference_hash/);
assert.match(privacyApi, /PRIVACY_REQUEST_TRANSITION_INVALID/);
assert.match(privacyApi, /RETENTION_POLICY_STALE/);
assert.match(privacyApi, /enforceTenantRateLimit/);
assert.match(backupApi, /snapshotDigestSha256/);
assert.match(backupApi, /RESTORE_TIMESTAMP_REQUIRED/);
assert.match(backupApi, /enforceTenantRateLimit/);
assert.match(readinessApi, /readyForProduction/);
assert.match(operational, /saas_integration_idempotency/);
assert.match(readinessApi, /correctiveActions/);
assert.match(readinessApi, /0016–0024/);
assert.match(keyringApi, /keyMaterialExposed: false/);
assert.match(keyringApi, /operationalCryptoReady/);
assert.match(keyringApi, /OPERATIONAL_DATA_KEY/);
assert.match(diagnosticsApi, /loadSaasSchemaPosture/);
assert.match(diagnosticsApi, /valuesExposed: false/);
assert.match(diagnosticsApi, /failClosed: true/);
assert.doesNotMatch(diagnosticsApi, /CLINICAL_DATA_KEY\s*:/);
assert.match(readinessHelper, /REQUIRED_SAAS_TABLES/);
assert.match(readinessHelper, /REQUIRED_SAAS_TRIGGERS/);
assert.match(inviteCreate, /tokenHash/);
assert.match(inviteCreate, /inviteEmailHash/);
assert.match(inviteCreate, /onRequestPatch/);
assert.match(inviteCreate, /INVITE_RESEND_CONFLICT/);
assert.match(inviteCreate, /replacedInviteId/);
assert.match(inviteCreate, /enforceTenantRateLimit/);
assert.match(inviteAccept, /INVITE_EMAIL_MISMATCH/);
assert.match(inviteAccept, /SEAT_LIMIT_REACHED/);
assert.match(fileRoutes, /LEGACY_FILE_ROUTE_DISABLED_IN_LIVE/);
assert.match(privacyMigration, /SAAS_AUDIT_APPEND_ONLY/);
assert.match(privacyMigration, /saas_privacy_requests/);
assert.match(inviteMigration, /SAAS_INVITE_SCOPE_IMMUTABLE/);
assert.match(integrationsMigration, /saas_integration_connections/);
assert.match(integrationsMigration, /SAAS_INTEGRATION_SCOPE_IMMUTABLE/);
assert.match(integrationsMigration, /SAAS_INTEGRATION_VERSION_CONFLICT/);
assert.match(idempotencyMigration, /SAAS_IDEMPOTENCY_IMMUTABLE/);
assert.match(idempotencyMigration, /SAAS_IDEMPOTENCY_APPEND_ONLY/);
assert.match(backupEvidenceMigration, /SAAS_BACKUP_EVIDENCE_APPEND_ONLY/);
assert.match(webhookMigration, /saas_webhook_deliveries/);
assert.match(webhookMigration, /SAAS_WEBHOOK_SCOPE_IMMUTABLE/);
assert.match(webhookMigration, /SAAS_WEBHOOK_APPEND_ONLY/);
assert.match(webhookApi, /operationalBlindHash/);
assert.match(webhookApi, /WEBHOOK_DELIVERY_REUSE/);
assert.match(webhookApi, /payloadStored: false/);
assert.match(webhookApi, /webhook.send/);
assert.match(webhookApi, /enforceTenantRateLimit/);
assert.match(observabilityApi, /payloadsExposed: false/);
assert.match(observabilityApi, /phiExposed: false/);
assert.match(observabilityApi, /crossTenantScope/);
assert.match(incidentsApi, /safeMetadata/);
assert.match(incidentsApi, /payloadStored: false/);
assert.match(incidentsApi, /INCIDENT_EVENT_INVALID/);
assert.match(incidentsApi, /enforceTenantRateLimit/);
assert.match(incidentMigration, /SAAS_INCIDENT_SCOPE_IMMUTABLE/);
assert.match(incidentMigration, /SAAS_INCIDENT_APPEND_ONLY/);
assert.match(rateLimitMigration, /saas_rate_limit_buckets/);
assert.match(rateLimitMigration, /SAAS_RATE_LIMIT_SCOPE_IMMUTABLE/);
assert.match(rateLimitHelper, /consumeTenantRateLimit/);
assert.match(rateLimitHelper, /TENANT_RATE_LIMITED/);
assert.match(rateLimitHelper, /Retry-After/);
assert.match(integrationsApi, /operationalBlindHash/);
assert.match(integrationsApi, /X-Idempotency-Key/);
assert.match(integrationsApi, /IDEMPOTENCY_KEY_REUSE/);
assert.doesNotMatch(integrationsApi, /credentialRef: row\.credential_ref/);
assert.match(integrationsApi, /SANDBOX_REQUIRED/);
assert.match(integrationsApi, /CLINICAL_SCOPE_REQUIRED/);
assert.match(integrationsApi, /enforceTenantRateLimit/);
assert.match(consolePage, /\/api\/saas\/integrations/);
assert.match(consolePage, /createInvite/);
assert.match(consolePage, /transitionPrivacyRequest/);
assert.match(consolePage, /\/api\/saas\/observability/);
assert.match(runbook, /readiness/);
assert.match(runbook, /Não é certificação LGPD/);
assert.match(productionGates, /confirm_production/);
assert.match(productionGates, /APPLY_PRODUCTION_MIGRATIONS/);
assert.match(productionGates, /pages secret list/);
assert.match(productionGates, /CLINICAL_LIVE_ENABLED/);
assert.match(productionGates, /metadata-only/);
assert.match(productionGates, /rollback_reference/);
assert.match(productionGates, /D1_DATABASE_NAME/);
assert.match(productionGates, /d1_database não corresponde ao D1 declarado/);
assert.match(productionGates, /0024_saas_rate_limit_buckets\.sql/);
assert.match(productionGates, /trg_saas_rate_limit_scope_immutable/);
assert.match(productionGates, /saas-migration-manifest/);
assert.match(migrationManifest, /SAAS_MIGRATION_MANIFEST_MISMATCH/);
assert.match(migrationManifest, /sha256/);
assert.match(migrationRollback, /forward-only/);
assert.match(migrationRollback, /down migration/);
assert.match(stagingEvidence, /secretsValuesExposed/);
assert.match(stagingEvidence, /remoteMigrationApplied/);
assert.match(productionGates, /Generate metadata-only staging evidence/);
assert.match(productionGates, /saas-staging-evidence\.json/);
assert.match(operational, /INTEGRATION_IDS = \[/);
assert.match(operational, /clinical\.read/);
assert.match(operational, /requiresSandbox/);
assert.match(operational, /MUTATION_STATES/);
assert.match(operational, /READINESS_CHECK_IDS/);
assert.match(operational, /WEBHOOK_REDACTION_RULES/);
assert.match(operational, /REQUIRED_SAAS_TABLES/);
assert.match(operational, /REQUIRED_SAAS_TRIGGERS/);
assert.match(operational, /webhook.send/);
assert.match(operational, /saas_webhook_deliveries/);
assert.match(operational, /saas_incident_events/);
assert.match(operational, /isValidIdempotencyKey/);
assert.match(operational, /isPrivacyRequestStatus/);
assert.match(consolePage, /pendingAction/);
assert.match(consolePage, /retentionDrafts/);
assert.match(consolePage, /resendInvite/);
assert.match(consolePage, /createIncident/);
assert.match(consolePage, /transitionIncident/);
console.log("[saas-production-hardening] ✓ contratos de tenant, LGPD, blind search, concorrência, continuidade, convites, integrações e fail-closed aprovados");
